project:
  type: website
  output-dir: _site

website:
  title: "Fangzhou Yu"
  description: "Personal website of Fangzhou Yu"
  site-url: https://fzy.netlify.app
  repo-url: https://github.com/miryo87s/quarto-website
  open-graph: true
  twitter-card: 
    creator: "@miryo87s"
    site: "@miryo87s"
    card-style: "summary_large_image"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: https://miryo87s.github.io/datadrivencv/cv.pdf
        text: Curriculum Vitae
      - href: research.qmd
      

format:
  html:
    theme: lumen
    css: styles.css
    toc: true
    toc-depth: 4
    toc-title: "Contents"
    html-math-method: katex
    include-in-header:
      - includes.html
    highlight-style: tango

